// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}
function errorResult(msg) {
  return { content: [{ type: "text", text: msg }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in Ide.On user's id, email and profile (full_name, church, city).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await sb.from("profiles").select("full_name, phone, church, city, instagram").eq("id", userId).maybeSingle();
    return jsonResult({ id: userId, email: ctx.getUserEmail(), profile });
  }
});

// src/lib/mcp/tools/list-sermons.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var list_sermons_default = defineTool2({
  name: "list_sermons",
  title: "List sermons",
  description: "List the signed-in user's sermons (id, status, summary, created_at), newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("How many sermons to return (max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("sermons").select("id, status, summary, created_at, transcription_time_ms").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-sermon.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_sermon_default = defineTool3({
  name: "get_sermon",
  title: "Get sermon",
  description: "Fetch a single sermon (transcript + summary) by id. Must belong to the signed-in user.",
  inputSchema: {
    id: z2.string().uuid().describe("The sermon id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("sermons").select("id, status, summary, transcript, created_at").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Sermon not found");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-content.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_content_default = defineTool4({
  name: "list_content",
  title: "List content library",
  description: "List items from the signed-in user's content library. Optional filters by content_type, pilar, status, and free-text search over title.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20),
    content_type: z3.string().optional().describe("Filter by content_type (e.g. 'Reel', 'Carrossel', 'Post')."),
    pilar: z3.string().optional().describe("Filter by strategic pillar."),
    status: z3.string().optional().describe("Filter by status (e.g. 'draft', 'published')."),
    search: z3.string().optional().describe("Case-insensitive title search.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, content_type, pilar, status, search }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    let q = sb.from("content_library").select("id, title, content_type, pilar, status, is_favorite, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (content_type) q = q.eq("content_type", content_type);
    if (pilar) q = q.eq("pilar", pilar);
    if (status) q = q.eq("status", status);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/get-content.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_content_default = defineTool5({
  name: "get_content",
  title: "Get content item",
  description: "Fetch a full content-library item (including the generated content JSON) by id.",
  inputSchema: {
    id: z4.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("content_library").select("id, title, content_type, pilar, status, content, tags, prompt_original, created_at, updated_at").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Content not found");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-volunteers.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_volunteers_default = defineTool6({
  name: "list_volunteers",
  title: "List volunteers",
  description: "List the signed-in user's volunteers.",
  inputSchema: {
    limit: z5.number().int().min(1).max(200).default(100),
    search: z5.string().optional().describe("Case-insensitive name search.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    let q = sb.from("volunteers").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 100);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-schedules.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_schedules_default = defineTool7({
  name: "list_schedules",
  title: "List volunteer schedules",
  description: "List volunteer schedule assignments for the signed-in user. Optionally filter by date range and status.",
  inputSchema: {
    limit: z6.number().int().min(1).max(200).default(100),
    from_date: z6.string().optional().describe("ISO date (YYYY-MM-DD) lower bound on service_date."),
    to_date: z6.string().optional().describe("ISO date (YYYY-MM-DD) upper bound on service_date."),
    status: z6.string().optional().describe("Filter by status (e.g. 'pending', 'confirmed', 'declined').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, from_date, to_date, status }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    let q = sb.from("volunteer_schedules").select("id, volunteer_id, service_date, service_name, start_time, end_time, role, status, notes, confirmed_at").eq("user_id", ctx.getUserId()).order("service_date", { ascending: true }).limit(limit ?? 100);
    if (from_date) q = q.gte("service_date", from_date);
    if (to_date) q = q.lte("service_date", to_date);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-church-sites.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_church_sites_default = defineTool8({
  name: "list_church_sites",
  title: "List church sites",
  description: "List church sites owned by the signed-in user (id, slug, is_published, published URL).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("church_sites").select("id, slug, is_published, created_at, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) return errorResult(error.message);
    const withUrl = (data ?? []).map((s) => ({ ...s, url: s.is_published ? `https://midias.app/igreja/${s.slug}` : null }));
    return jsonResult(withUrl);
  }
});

// src/lib/mcp/index.ts
var projectRef = "imitktxtunqovyqsmplb";
var mcp_default = defineMcp({
  name: "ideon-mcp",
  title: "Ide.On",
  version: "0.1.0",
  instructions: "Ide.On \xE9 uma plataforma de conte\xFAdo digital para igrejas. Use estas ferramentas para consultar, em nome do usu\xE1rio autenticado, seus serm\xF5es, biblioteca de conte\xFAdos, volunt\xE1rios, escalas e sites de igreja. Todas as leituras respeitam RLS: o usu\xE1rio s\xF3 v\xEA os pr\xF3prios dados.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_sermons_default, get_sermon_default, list_content_default, get_content_default, list_volunteers_default, list_schedules_default, list_church_sites_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
